AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kt-dynamodb-with-single-table-design

  Sample SAM Template for kt-dynamodb-with-single-table-design

Globals:
  Function:
    Timeout: 60
    CodeUri: backend/
    Environment:
      Variables:
        DATABASE_NAME: kt-dynamodb

Resources:
  KTDynamoTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: kt-dynamodb
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SeedUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: seed-users.seedUsers
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/user/seed-users.ts

  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-user.getUser
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/user/get-user.ts

  ListUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list-users.listUsers
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/user/list-users.ts

  ListPaginateUsers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list-paginate-users.listPaginateUsers
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/user/list-paginate-users.ts

  # CreateBalance:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: create-balance.createBalance
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - src/lambdas/balance/create-balance.ts

  # GetBalance:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: get-balance.getBalance
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - src/lambdas/balance/get-balance.ts

  ListBalancesByWallet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: list-balances-by-wallet.listBalancesByWallet
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/balance/list-balances-by-wallet.ts

  # ListBalancesByAsset:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: list-balances-by-asset.listBalancesByAsset
  #     Runtime: nodejs20.x
  #     Architectures:
  #       - x86_64
  #   Metadata:
  #     BuildMethod: esbuild
  #     BuildProperties:
  #       Minify: true
  #       Target: "es2020"
  #       Sourcemap: true
  #       EntryPoints:
  #         - src/lambdas/balance/list-balances-by-asset.ts

  Seed:
    Type: AWS::Serverless::Function
    Properties:
      Handler: seed.seed
      Runtime: nodejs20.x
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/lambdas/seed.ts
